import { openai } from "@ai-sdk/openai";
import { generateObject } from "ai";
import { z } from "zod";

// Define the schema for cleaned recipe, tags, and structured fields.
// baseServings and ingredients are lenient (default to safe values) so a
// partial model response still validates and the recipe still saves —
// the structured stepper hides itself when ingredients is empty.
const RecipeProcessingSchema = z.object({
  cleanedInstructions: z
    .string()
    .describe("Cleaned and formatted recipe instructions"),
  tags: z
    .array(z.string())
    .default([])
    .describe("Array of relevant recipe tags"),
  baseServings: z
    .number()
    .int()
    .positive()
    .default(2)
    .describe(
      "How many servings the recipe yields as written. If unstated, infer a sensible default (typically 2-4).",
    ),
  ingredients: z
    .array(
      z.object({
        name: z.string().describe("Ingredient name, e.g., 'chicken breast'"),
        amount: z
          .number()
          .positive()
          .optional()
          .describe(
            "Numeric amount if stated. Omit for non-quantified ingredients (e.g., 'salt to taste').",
          ),
        unit: z
          .string()
          .optional()
          .describe(
            "Unit string matching the recipe text (e.g., 'g', 'tbsp', 'cup', 'piece'). Omit if amount is omitted.",
          ),
      }),
    )
    .default([])
    .describe(
      "Structured ingredient list extracted from the recipe. Use the exact unit strings the recipe uses so the app can compute shortfalls against inventory.",
    ),
});

export type RecipeProcessingResult = z.infer<typeof RecipeProcessingSchema>;

// Comprehensive tag categories for the AI to choose from
const TAG_CATEGORIES = `
CUISINE TYPES: italian, chinese, japanese, mexican, indian, thai, french, mediterranean, american, korean, vietnamese, middle-eastern, greek, spanish, moroccan

PROTEIN TYPES: chicken, beef, pork, fish, seafood, vegetarian, vegan, eggs, tofu, beans, lentils

COOKING METHODS: baked, fried, grilled, steamed, boiled, roasted, sauteed, stir-fried, braised, slow-cooked, pressure-cooked, air-fried, no-cook, raw, marinated, fermented, pickled, preserved

MEAL TYPES: breakfast, lunch, dinner, snack, appetizer, dessert, side-dish, main-course, soup, salad, beverage

DIFFICULTY: beginner, easy, intermediate, advanced, quick (under 30 min), one-pot, make-ahead

TEXTURE/STYLE: crispy, creamy, spicy, sweet, savory, tangy, hearty, light, refreshing, warming

SPECIAL EQUIPMENT: wok, instant-pot, cast-iron, slow-cooker, blender, oven-free, grill
`;

export async function processRecipe(
  recipeName: string,
  recipeInstructions: string,
): Promise<RecipeProcessingResult> {
  const prompt = `
You are processing a recipe called "${recipeName}" for permanent storage in a cooking app.

RECIPE CONTEXT:
- This recipe was generated by an AI cooking assistant that has a warm granny personoa and speaks with a mix of English and Singlish
// …other prompt lines…
- This recipe was generated by an AI cooking assistant that has a warm granny persona and speaks with a mix of English and Singlish
// …possibly more lines…
- The recipe will be saved, shared, and referenced later by users
// …subsequent code…
You need to do FOUR tasks for this recipe:

1. CLEAN the recipe instructions for permanent storage
2. GENERATE 3-8 relevant tags
3. EXTRACT baseServings — the number of servings the recipe yields as written (infer a sensible default like 2 or 4 if unstated)
4. EXTRACT ingredients — a structured list of every ingredient with name, optional amount, and optional unit. Use the exact unit strings the recipe uses. Omit amount/unit for non-quantified items like "salt to taste" or "a pinch of pepper".

CLEANING RULES:
- Remove UI-specific symbols like ✅ (checkmarks) and 🛒 (shopping cart icons)
- Keep cooking-related emojis (🔥, 🍳, 🥄, etc.) as they add value
- Ensure proper markdown formatting with clear sections
- Keep ingredient lists and instructions well-structured
- Remove any redundant spacing or formatting artifacts
- Maintain the recipe's original tone and personality
- Keep all essential cooking information intact
- Format for long-term storage and easy sharing

TAGGING RULES:
- Choose 3-8 most relevant tags from the categories below
- Use exact tag names from the categories (lowercase, hyphenated)
- Focus on cuisine, protein, cooking method, meal type, and distinctive characteristics
- Avoid generic tags unless they're very relevant
- Consider dietary restrictions if obvious from ingredients

AVAILABLE TAG CATEGORIES:
${TAG_CATEGORIES}

RECIPE NAME: ${recipeName}

RECIPE INSTRUCTIONS TO PROCESS:
${recipeInstructions}

Return the cleaned instructions, tags, baseServings, and ingredients in the specified JSON format.`;

  const result = await generateObject({
    model: openai("gpt-4.1-mini"),
    schema: RecipeProcessingSchema,
    prompt,
    temperature: 0.2, // Low temperature for consistent processing
  });

  return result.object;
}
