export type Recipe = {
  userId: string;
  name: string;
  instructions: string;
  tags?: string[];
  recipeId?: string; // Unique ID generated by AI for each recipe
};

export type RecipeWithId = Recipe & { id: string };
